---
- name: Ensure dependencies are installed.
  ansible.builtin.package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - virtualenv
      - lsb-release
      - mkisofs
    state: present

- name: Ensure additional dependencies are installed (on Ubuntu < 20.04 and any other systems).
  ansible.builtin.package:
    name: gnupg2
    state: present
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_version is version('20.04', '<')

- name: Ensure additional dependencies are installed (on Ubuntu >= 20.04).
  ansible.builtin.package:
    name: gnupg
    state: present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution_version is version('20.04', '>=')
